# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

RUN apt-get update && apt-get install -y libxrender1 && apt-get install -y libxrender1 && apt-get install -y   libxtst6 && apt-get install -y libxi6 && apt-get install -y libexpat-dev
# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir .

# Make port 80 available to the world outside this container
EXPOSE 80

# Run mcp_simple_arxiv when the container launches
ENTRYPOINT ["python", "-m", "mcp_rdkit"]